name: "snyk code test"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - name: Authenticate Snyk
        run: snyk auth $SNYK_TOKEN
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - name: Snyk Test
        run: snyk code test --org=70c42caa-d4ab-400b-92e2-0694aff64d96 --sarif > snyk-sarif2.json
        continue-on-error: true
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - name: Monitor Project in Snyk
        run: snyk monitor --org=70c42caa-d4ab-400b-92e2-0694aff64d96
        env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Display json
        run: cat snyk-sarif2.json
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-sarif2.json
