name: "Bomber SBOM Scan"

on: [push, pull_request]

jobs:
  sbom-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node packages
        run: npm install 

      - name: Install Latest Bomber
        run: |
          wget https://github.com/devops-kung-fu/bomber/releases/download/v0.5.1/bomber_0.5.1_linux_amd64.deb
          sudo dpkg -i bomber_0.5.1_linux_amd64.deb
          
      - name: Create SBOM with CycloneDX
        uses: CycloneDX/gh-node-module-generatebom@v1
        with: 
          output: './mysbom.json'

      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-bomber
          path: mysbom.json

      - name: Verify SBOM File
        run: ls -l mysbom.json

      - uses: snyk/actions/setup@master
          
      - name: Scan SBOM with Snyk (via Bomber)
        run: |
          # SNYK_API=https://api.eu.snyk.io bomber scan --provider snyk --token ${{ secrets.SNYK_TOKEN }} mysbom.json
            SNYK_API=https://api.eu.snyk.io bomber scan --provider snyk --token 5bbbd5e5-6a79-4c19-8c95-bfbb5ec36b13 mysbom.json
      
